### ISSUE TITLE
No solder jumper present on board for DI (I2C address select) pin

### ISSUE THREAD

**Issue by StarWitch** [adafruit/Adafruit-BNO08x-PCB#1]
Hi there. I was going through the  [BNO08x Tutorial](https://learn.adafruit.com/adafruit-9-dof-orientation-imu-fusion-breakout-bno085/pinouts) and saw mention of this:

>DI - I2C Address pin. Pulling this pin high or **_bridging the solder jumper on the back_** will change the I2C address from 0x4A to 0x4B

However, looking at the .brd file I noticed there isn't a solder jumper for the DI pin.

<img width="124" alt="image" src="https://user-images.githubusercontent.com/34408664/104053608-92492980-51b9-11eb-961f-a639f9ab87c3.png">

Was there intended to be one, or is the documentation incorrect?

**Comment by ladyada** [comment]
typo in dox. fixed now!
