### ISSUE TITLE
Add LED jumper

### ISSUE THREAD

**Issue by adamgarbo** [adafruit/Adafruit-BNO08x-PCB#2]
Hi folks,

I would like to make the suggestion to add a jumper to allow users to easily disable/enable the LED on the BNO085. Physically cutting the trace or removing the LED with a hot air rework station is not always an ideal solution for users.

It'd be great to see the LED jumper included as part of the standard STEMMA design to help decrease the current consumption for low power operation.

Cheers,
Adam

**Comment by ladyada** [comment]
ok!
